/*
 * Licensed under the LICENSE.
 * Copyright 2017, Sony Mobile Communications Inc.
 */

var PORT_SERVER_DESC_TESTS = 13380;
var PORT_PM_SERVER_TESTS = 14370;
var PORT_JOB_SERVER_TESTS = 13360;
var PORT_PM_SERVER_TESTS_NGINX = 1337;
var PORT_JOB_SERVER_TESTS_NGINX = 1336;
var CATEGORY = 'default';
var UUID = "DUMMY_UUID";

module.exports = {
	PORT_SERVER_DESC_TESTS: PORT_SERVER_DESC_TESTS,
	PORT_PM_SERVER_TESTS: PORT_PM_SERVER_TESTS,
	PORT_JOB_SERVER_TESTS: PORT_JOB_SERVER_TESTS,
	PORT_PM_SERVER_TESTS_NGINX: PORT_PM_SERVER_TESTS_NGINX,
	PORT_JOB_SERVER_TESTS_NGINX: PORT_JOB_SERVER_TESTS_NGINX,
	CATEGORY: CATEGORY,
	UUID: UUID
};
