#!/bin/bash

BASE_DIR="`pwd`"
INSTALL_DIR="`pwd`/fftw-3.3.6/build"
SRC_DIR="`pwd`/fftw-3.3.6"

export PROJECT_PATH=$PWD
export CURRENT_DIR=$PROJECT_PATH
export TOOLCHAIN=$CURRENT_DIR/android-toolchain
export ANDROID_NDK=$1
mkdir -p $TOOLCHAIN
$ANDROID_NDK/build/tools/make-standalone-toolchain.sh \
    --toolchain=aarch64-linux-android-4.9 \
    --arch=arm64 \
    --install-dir=$TOOLCHAIN \
    --platform=android-21 \
    --force

cd $SRC_DIR
export PATH="$BASE_DIR/android-toolchain/bin/:$PATH"
export SYS_ROOT="$BASE_DIR/android-toolchain/sysroot"
export CC="aarch64-linux-android-gcc --sysroot=$SYS_ROOT"
export LD="aarch64-linux-android-ld"
export AR="aarch64-linux-android-ar"
export RANLIB="aarch64-linux-android-ranlib"
export STRIP="aarch64-linux-android-strip"

mkdir -p $INSTALL_DIR

./configure --host=aarch64 --disable-doc --enable-float --enable-neon --enable-threads --enable-shared=yes --prefix=$INSTALL_DIR LIBS="-lc -lgcc"

make -j 4

make install
