/*
 * Licensed under the LICENSE.
 * Copyright 2017, Sony Mobile Communications Inc.
 */

// HTTP response status codes
var STATUS_CODE_OK = 200;
var STATUS_CODE_NO_CONTENT = 204;
var STATUS_CODE_EMPTY_QUEUE = 304;
var STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
var STATUS_CODE_SERVICE_UNAVAILABLE = 503;
var STATUS_CODE_NOT_FOUND = 404;
var STATUS_CODE_FORBIDDEN = 403;

// ports
var PORT_JOB_SERVER = 13360;
var PORT_PM_CONNECTION_POINT = 14370;
var PORT_JOB_LISTEN_MIN = 1024;
var PORT_JOB_LISTEN_MAX = 65536;

// Job consts
var DATA_JOB_SERVER_MAX = 1024;
var DATA_JOB_PATH_MAX = 4096;
var JOB_COUNT_MIN = 0;
var JOB_COUNT_MAX = 1024;
var JOB_ESTIMATION_UPDATE_TIME = 1; //seconds
var JOB_ESTIMATION_UPDATE_TIME_MS = JOB_ESTIMATION_UPDATE_TIME * 1000; //miliseconds
//1 minute = JOB_ESTIMATION_UPDATE_TIME * JOB_ESTIMATION_RATE_STORED
var JOB_ESTIMATION_RATE_STORED = 60;
var TIMEOUT_REQUEST = 60000;
var PROJECT_ATTRIBUTES_OID = '1.2.3.4.5';
var NUMBER_OF_USERS_KEY = 'number_of_users';
// timeout to flush the new logs.
var FLUSH_LOGGLY_QUEUE_TIMEOUT = 300000;
// Max size for the log queue.
var LOGGLY_QUEUE_MAX_SIZE = 5000;

var sony_buckets = {
  Jobscripts: '-jobscripts', // This will be appended to the instance name
  JobserverFiles: '-jobserver-files', // This will be appended to the instance name
  VersionMappingFile: 'version_mapping.json',
  PreviousCacheFile: 'previous-cache.json'
};

current_buckets = sony_buckets;


/**
  Exports
*/
module.exports = {
  STATUS_CODE_OK: STATUS_CODE_OK,
  STATUS_CODE_NO_CONTENT: STATUS_CODE_NO_CONTENT,
  STATUS_CODE_EMPTY_QUEUE: STATUS_CODE_EMPTY_QUEUE,
  STATUS_CODE_INTERNAL_SERVER_ERROR: STATUS_CODE_INTERNAL_SERVER_ERROR,
  STATUS_CODE_NOT_FOUND: STATUS_CODE_NOT_FOUND,
  STATUS_CODE_SERVICE_UNAVAILABLE: STATUS_CODE_SERVICE_UNAVAILABLE,
  STATUS_CODE_FORBIDDEN: STATUS_CODE_FORBIDDEN,
  PORT_JOB_SERVER: PORT_JOB_SERVER,
  PORT_PM_CONNECTION_POINT: PORT_PM_CONNECTION_POINT,
  PORT_JOB_LISTEN_MIN: PORT_JOB_LISTEN_MIN,
  PORT_JOB_LISTEN_MAX: PORT_JOB_LISTEN_MAX,
  DATA_JOB_SERVER_MAX: DATA_JOB_SERVER_MAX,
  DATA_JOB_PATH_MAX: DATA_JOB_PATH_MAX,
  JOB_COUNT_MIN: JOB_COUNT_MIN,
  JOB_COUNT_MAX: JOB_COUNT_MAX,
  JOB_ESTIMATION_UPDATE_TIME: JOB_ESTIMATION_UPDATE_TIME,
  JOB_ESTIMATION_UPDATE_TIME_MS: JOB_ESTIMATION_UPDATE_TIME_MS,
  JOB_ESTIMATION_RATE_STORED: JOB_ESTIMATION_RATE_STORED,
  TIMEOUT_REQUEST: TIMEOUT_REQUEST,
  PROJECT_ATTRIBUTES_OID: PROJECT_ATTRIBUTES_OID,
  NUMBER_OF_USERS_KEY: NUMBER_OF_USERS_KEY,
  BUCKETS: current_buckets,
  FLUSH_LOGGLY_QUEUE_TIMEOUT: FLUSH_LOGGLY_QUEUE_TIMEOUT,
  LOGGLY_QUEUE_MAX_SIZE: LOGGLY_QUEUE_MAX_SIZE
};
